### ISSUE TITLE
css name not found - Getting field from Page Layout

### ISSUE THREAD

**Issue by goldylamba** [forcedotcom/cinnamon#26]
While writing a code in PageObject class to access a field on page layout edit UI page, I am receving an error in the test console as  "css name is not found" in PageObjectClass.

//Code snippet from Page Object class
public override void initializePageObject() 
    {
       
        sName = getElement(new cinnamon.StandardLayoutLocator('#Name')); // I am facing problem in this line. I am not able to access 'Name' field (or any other field) from Page layout. But able to do similar thing for a visualforce page.
        sAudience = getElement(new cinnamon.ElementLocator('#00No00000069ep5'));
        saveBtn = getElement(new cinnamon.ElementLocator('input[name="save"]'));

    }
![image](https://cloud.githubusercontent.com/assets/9477743/4858104/650cc426-60da-11e4-8dab-56c540341e2d.png)

**Comment by yudiatsfdc** [comment]
No response from initiator, assuming issue is resolved
