### ISSUE TITLE
Failed to download Selenium User Extension error

### ISSUE THREAD

**Issue by nitinkhandelwal03** [forcedotcom/cinnamon#29]
Failed to download Selenium User Extension: http://cinnamon-prod-developer-edition.na14.force.com/userextensions

error

Getting this error when I am run my cinnamon test scripts on saucelabs.Initially they were working fine and i was able to execute the scripts properly. The same scripts are giving this error now.

Thanks,
Nitin

**Comment by yudiatsfdc** [comment]
Our next release will remove the dependency on this script so you should be able to run your tests without these incidents
