### ISSUE TITLE
Regression: Things that used to work on Beta are broken in Spring Manage Package 1.1

### ISSUE THREAD

**Issue by rmadakasira** [forcedotcom/cinnamon#35]
Hi,

The below code complains of "Error: Compile Error: Abstract class cannot be constructed: cinnamon.ElementLocator at line 24 column 28".

It works fine for the VisualForceLocators but not for the "ElementLocators". Are there any changes around this. I don't see any update on the Documentation though. 

"public class CinnamonAccountPageObject extends cinnamon.PageObject {

```
 public cinnamon.ElementLocator accountTabLoc,

public override void initializePageObject() {
    accountTabLoc=new cinnamon.ElementLocator('#Account_Tab > a');"
```

}
}

**Comment by rmadakasira** [comment]
Looks like the ElementLocator is an abstract class now. However, the Documentation say it is not, as it was not in Beta too.

Is there any specific reason for this change between the Beta version and the new Manage Package. All of my tests are blocked due to this.

Appreciate a speedy response to this. Thanks.

**Comment by jheritagesf** [comment]
@rmadakasira It is an abstract class now. The documentation is a little behind, but it should be updated by the end of this week.

**Comment by rmadakasira** [comment]
Is there a work-around for me ? All of my PageObjects are based on the ElementLocator. 

Any tips ? 

Appreciate your help.

**Comment by jheritagesf** [comment]
@yudiatsfdc @nadeemg Could you advise?

**Comment by nadeemg** [comment]
@rmadakasira could you take a look at CSSLocator? I think that should do it.

**Comment by rmadakasira** [comment]
Yes. This worked. Thanks.
