### ISSUE TITLE
Question on Documentation Steps: Don't you need to install "Apex Selenium Client" for Cinnamon

### ISSUE THREAD

**Issue by rmadakasira** [forcedotcom/cinnamon#36]
I remember on Beta Version we had to install "Apex Selenium Client" as well.

Documentation does not indicate if we need "Apex Selenium Client". Please confirm. Thanks.

**Comment by yudiatsfdc** [comment]
Thanks for bringing it up. There's no need for that package anymore.

**Comment by rmadakasira** [comment]
Perfect. Thanks.
