### ISSUE TITLE
Max Duration (Sauce) Error

### ISSUE THREAD

**Issue by smeridew** [forcedotcom/cinnamon#6]
![screenshot 2014-07-03 12 27 22](https://cloud.githubusercontent.com/assets/6664268/3472741/55ed3174-02cf-11e4-9bed-019bcfe4c3a5.png)

Timeout was with:

Test Name	TestSampleCinnamonTest	 TestSuite	0000
Execution Status	Passed	 Result	Passed
OS	OS X 10.6	 Browser	firefox
Browser Version	18	 Test Rerun	Not Checked

No Timeout was with:

Test Name	TestSampleCinnamonTest	 TestSuite	0001
Execution Status	Passed	 Result	Passed
OS	Windows 8	 Browser	firefox
Browser Version	18	 Test Rerun	Not Checked

**Comment by yudiatsfdc** [comment]
http://forcedotcom.github.io/cinnamon/news/2014/12/12/cinnamon-aws-swd/
